---
title: "chapter_01"
format: html
editor: source
html:
  self-contained: true
---

```{r}
#| message: false
# libraries 
library(tidyverse)
library(Lahman)
library(patchwork)
```


### Question 1.2.8 
What is the averaged number of home runs per game recorded in each decade? Does the rate of strikeouts show any correlation with the rate of home runs?

First, we need to get the data for home runs per game.  
```{r}
#| message: false
#| code-fold: true

# get Lahman team data 
teams = Lahman::Teams

# get home runs by decade 
home_run_by_decade = teams %>% 
  mutate(decade = paste(substr(yearID, 1, 3), 0, sep = "")) %>% 
  group_by(decade) %>% 
  summarize(total_hr = sum(HR), total_g = (sum(G)/2), total_k = sum(SO, na.rm = T), hrpg = total_hr/total_g, kpg = total_k/total_g) %>% 
  ungroup()
```

Now we can graph this table to look at the three questions of interest. First, what is the average number of home runs per game for each decade. 

```{r}
# graph of home runs by decade 
ggplot(home_run_by_decade, aes(decade, hrpg))+
  geom_point()+
  geom_line(aes(group = 1))+
  theme_minimal()+
  labs(
    title = "Home Runs Per Game by Decade",
    x = "Decade",
    y = "Home Runs Per Game"
  ) +
  theme(
    plot.title = element_text(face = "bold", size = 16)
  )
```
```{r}
# strike outs per game by decade 
ggplot(home_run_by_decade, aes(decade, kpg)) + 
  geom_point() + 
  geom_line(group = 1) +
  theme_minimal() +
  labs(
    title = "Strike Outs Per Game",
    x = "Decade", 
    y = "Strikeouts Per Game"
  ) + 
  theme(
    plot.title = element_text(face = "bold", size = 20)
  )
```
```{r}
# both mapped together 
plot1 = ggplot(home_run_by_decade, aes(as.numeric(decade), hrpg))+
  geom_point(color = "darkblue")+
  geom_line(aes(group = 1), color = "darkblue")+
  theme_minimal()+
  labs(
    title = "Relationship Between Home Runs and Strikeouts by Decade",
    subtitle = "Home Runs per Game",
    x = NULL, 
    y = NULL
  ) +
  theme(
    plot.title = element_text(face = "bold", size = 16),
    plot.subtitle = element_text(face = "italic")
  )

plot2 = ggplot(home_run_by_decade, aes(as.numeric(decade), kpg)) + 
  geom_point(color = "darkred") + 
  geom_line(group = 1, color = "darkred") +
  theme_minimal() +
  labs(
    subtitle = "Strikeouts Per Game",
    x = NULL, 
    y = NULL
  ) + 
  theme(
    plot.subtitle = element_text(face = "italic")
  )

plot1 + plot2
```

```{r}
home_run_by_decade %>% 
  pivot_longer(cols = hrpg:kpg, names_to = "stat", values_to = "spg") %>% 
  mutate(decade = as.numeric(decade)) %>% 
  ggplot(aes(decade, spg, color = stat))+
  geom_point()+
  geom_line()+
  scale_color_manual(values = c("darkblue","darkred"), labels = c("Home Runs", "Strikouts"))+
  theme_minimal()+
  labs(
    title = "Relationship Between Home Runs and Strikeouts by Decade",
    x = "Decade",
    y = "# per Game",
    color = NULL
  )+
  theme(
    plot.title = element_text(face = "bold"),
    legend.position = "bottom"
  )
```

```{r}
#| warning: false
# looking at percent change 
home_run_by_decade %>% 
  mutate(hr_delta = (hrpg - lag(hrpg))/lag(hrpg)*100,
         k_delta = (kpg - lag(kpg))/lag(kpg)*100) %>% 
  select(decade, hr_delta, k_delta) %>% 
  mutate(decade = as.numeric(decade)) %>% 
  pivot_longer(cols = hr_delta:k_delta, names_to = "stat", values_to = "value") %>% 
  ggplot(aes(x = decade, y = value, color = stat))+
  scale_color_manual(values = c("darkblue","darkred"), labels = c("Home Runs", "Strikeouts"))+
  geom_point()+
  geom_line()+
  theme_minimal()+
  labs(
    title = "Percent Change in HRs and Ks by Decade",
    x = "Decade",
    y = "Percent Change",
    color = NULL
  )+
  theme(
    plot.title = element_text(face = "bold"),
    axis.title = element_text(face = "italic"),
    legend.position = "bottom"
  )
```


